services:
  analysis-env:
    build: . # Build from my local Dockerfile
    image: tracywxr/dockerfile-practice # My custom image name
    ports:
      - "8787:8787"
    volumes:
      - .:/home/rstudio/folder1
    environment:
      PASSWORD: "password"
      DISABLE_AUTH: true